### ISSUE TITLE
域名/admin.php后出现错误,看你的介绍,改为app()->user

### ISSUE THREAD

**Issue by wujianan** [lea21st/leacmf-thinkphp#10]
域名/admin.php后出现错误,看你的介绍,改为app()->user
![image](https://user-images.githubusercontent.com/26913481/40642424-a8f692f4-634f-11e8-9e68-339cb1277b70.png)  换了其他写法  还是找不到类 暂时注释掉了  不忙的时候希望解答一下 谢谢

**Comment by lea21st** [comment]
已修复
