### ISSUE TITLE
我重新下了  还是 这个问题   

### ISSUE THREAD

**Issue by wujianan** [lea21st/leacmf-thinkphp#11]
![image](https://user-images.githubusercontent.com/26913481/40820404-e8faad64-6592-11e8-8aa3-85822e68202c.png)
我重新下了  还是 这个问题   有什么解决办法 吗

**Comment by lea21st** [comment]
composer update 用了吗

**Comment by zhibiao2014** [comment]
/admin/public/login

**Comment by MeMadMan** [comment]
publicController 里面 app()->user 改为 app()->rbac->user()

**Comment by lea21st** [comment]
empty(app()->user)
