### ISSUE TITLE
关于后台中间件Rbac类：无no_need_login_url

### ISSUE THREAD

**Issue by zhuojiawei** [lea21st/leacmf-thinkphp#16]
```
   protected $config = [
        'auth_on'           => 1, // 权限开关
        'auth_type'         => 1, // 认证方式，1为实时认证；2为登录认证。
        'auth_group'        => 'auth_group', // 用户组数据表名
        'auth_group_access' => 'auth_group_access', // 用户-用户组关系表
        'auth_rule'         => 'auth_rule', // 权限规则表
        'auth_user'         => 'admin', // 用户信息表
    ];
```

````

    /**
     * 校验url，是否需要用户验证
     * @return bool
     */
    public function notNeedLogin()
    {

        $urls = $this->config['no_need_login_url'];
        if (in_array($this->getPath(), $urls)) {
            return true;
        }
        return false;
    }

````

** 在RBAC类中出现：未定义数组索引: no_need_login_url**

**Comment by lea21st** [comment]
在响应的模块下新增auth.php配置文件。内容可以是
`
return [
    'auth_on'           => 1, // 权限开关
    'auth_type'         => 1, // 认证方式，1为实时认证；2为登录认证。
    'auth_group'        => 'auth_group', // 用户组数据表名
    'auth_group_access' => 'auth_group_access', // 用户-用户组关系表
    'auth_rule'         => 'auth_rule', // 权限规则表
    'auth_user'         => 'admin', // 用户信息表

    //不需要登录的
    'no_need_login_url' => [
        '/public/login'
    ],

    //登录用户不需要验证的
    'allow_visit'       => [
        '/public/',
        '/index/',
        '/file/upload',
        '/info/',
    ]
];`
如admin模块，在/config/admin/auth.php中添加no_need_login_url即可，或者在这儿判断下
